### ISSUE TITLE
Problem: list of tracks in current album cut off at last played track

### ISSUE THREAD

**Issue by improvius** [MoleMan1024/audiowagon#78] opened 2022-07-23 02:29 UTC
This problem happens when playing an album, stopping at least two tracks in, leaving the car for a while, and then resuming playback after getting back in. The track for the current album will no longer contain any songs prior to the current song. For example:

1. Album A has 10 tracks.
2. Select Album A from album list tab, and start playback.
3. The current track list will contain all 10 tracks.
4. Start playback of track 4.
5. Get out and leave car locked for a while.
6. Get back in car and resume playback.
7. Playback will resume with track 4.
8. The current track list will only contain tracks 4-10.
9. To replay any previous tracks (1-3), you must go back to the album list and re-select the album.

Also, thank you again for making this app!

**Comment by MoleMan1024** [comment] 2022-07-23 06:41
Thanks for the bug report. This is actually the intended behaviour. But it has been asked about before, so maybe it is a bit confusing.

**Comment by MoleMan1024** [comment] 2022-07-23 10:03
This was intended to store the least amount of data possible in flash memory, but I guess the amount of data that I save by dropping old items from the playback queue is negligible (a few kilobytes in best case).

**Comment by MoleMan1024** [comment] 2022-08-20 16:41
This is fixed in version 2.2.1

**Closed by MoleMan1024** 2022-08-20 16:41 UTC
Labels: enhancement, change_prepared
