### ISSUE TITLE
Audiowagon usb access

### ISSUE THREAD

**Issue by WimvanDijk** [MoleMan1024/audiowagon#155] opened 2024-09-03 20:44 UTC
Audiowagon can not access to usb when driving, only when car is not moving. Before the car update is wasxworking well, you only must give access after every car start. But this popup comes not when driving. Not allowed when driving, 

 Wim van dijk, volvo 2022 xc60

**Comment by MoleMan1024** [comment] 2024-09-04 05:18
Duplicate of https://github.com/MoleMan1024/audiowagon/issues/142

**Closed by MoleMan1024** 2024-09-04 05:18 UTC
Labels: enhancement
