### ISSUE TITLE
Allow AudioWagon to access USB DISK 3.0 persistant popup

### ISSUE THREAD

**Issue by kingstonwa** [MoleMan1024/audiowagon#133] opened 2023-12-20 18:28 UTC
**Describe the issue**
I have a 2023 C40 and connected a USB flash drive to the usb port with the white circle. When I launch Audiowagon, I get this popup persistently repeated every time I start. The developer tells me that this is a Volvo system issue. How can I disable this popup?

**To Reproduce**
1. install Audiowagon
2. insert properly formatted usb drive in the proper usb port
3. let audiowagon digest the files
4. turn off system and exit car
5. enter car and launch audiowagon
6. see persistent popup requiring OK to Allow AudioWagon to access USB DISK 3.0 and check the box for Always open... perm
7. exit system, then enter car and launch audiowagon, see repeated issue described in 6. above

**Expected behavior**
No popup after first interaction and OK selected

**AudioWagon version**
<Which version of AudioWagon were you using? (see the settings screen)>

**Car version**
Updated on
Nov 4, 2023 from Google Play download

![IMG_20231208_095942820_HDR_AE](https://github.com/MoleMan1024/audiowagon/assets/71231040/6b90a5f3-6a35-4631-804f-2eb798678b23)

**Comment by MoleMan1024** [comment] 2023-12-20 18:30
This is already addressed in the [FAQ](https://moleman1024.github.io/audiowagon/faq.html#why-does-the-permission-popup-appear-each-time-the-always-open-audiowagon--checkbox-does-not-do-anything). Must be fixed by Volvo/Polestar in Android Automotive code. 3rd party apps do not have permission to set themselves as default Intent handlers for USB intents, this must be done by the OEM.

**Closed by MoleMan1024** 2023-12-20 18:30 UTC
Labels: bug

**Comment by bobybc** [comment] 2024-01-29 06:31
I just want to say that the same issue occurs on Renault Megane E-TECH

**Comment by petard** [comment] 2024-04-25 13:10
Volvo / Polestar released an update to Android 12 from Android 11 recently. Does it make any difference on how to resolve this issue?

**Comment by micksmothers** [comment] 2024-04-25 13:56
I think we can only hope - I am running the update on my Polestar 2 right now, I'll test it out once the update is successfully completed.

**Comment by kingstonwa** [comment] 2024-04-25 22:13
Just updated to v 3 on my Volvo C40 and no joy, blue popup still comes on

**Comment by micksmothers** [comment] 2024-04-26 18:31
Yes, same here with my Polestar unfortunately. I'm used to just tapping the button every time I get in the car. Annoying but not horribly so.

**Comment by kingstonwa** [comment] 2024-04-26 18:58
Anyone having this issue, I encourage you to contact Volvo on their Facebook messanger chat and ask that this be fixed. Perhaps some squeeky wheels will motivate them https://www.messenger.com/t/339744344488

**Comment by MoleMan1024** [comment] 2024-05-17 13:51
Based on some recent logging changes I made, I found that in certain cars that report themselves as a device called "OpenR Link" (I believe those are Renault cars), the USB permission is granted during boot-up.

Even though @bobybc said above the permission popup also appears in those cars (which can be true, depending on timing), in most cases *it should not appear*, the permission will be granted automatically (like I would expect in Polestar/Volvo cars also).

Attached is a log file as proof: [de.moleman1024.audiowagon_issue_9d4a11dec5864345ec38522d6bb2158b_error_session_6646EB7503D0000137F4D02FF64B80BA_DNE_0_v2.log](https://github.com/MoleMan1024/audiowagon/files/15349883/de.moleman1024.audiowagon_issue_9d4a11dec5864345ec38522d6bb2158b_error_session_6646EB7503D0000137F4D02FF64B80BA_DNE_0_v2.log)

In that log file, the AudioBrowserService is first created here at 07:30:30 CEST:
```
2024-05-17 07:30:30.060 [DEBUG   ][14324-14324][AudioBrowserService     ] onCreate() at: 2024-05-17T07:30:30.059+0200↲
```
AudioWagon could initialize the filesystem 3.1 minutes after the system was booted, so we know the car was not in sleep mode before, it is a cold boot (the uptimeMillis equals the elapsedRealtime and it is only 187078 milliseconds ~ 3.1 minutes):
```
2024-05-17 07:30:31.309 [INFO    ][14324-14413][USBDevConn              ] Successfully initialized filesystem at: 2024-05-17T07:30:31.309+0200 (uptimeMillis=187078 elapsedRealtime=187078)↲
```
In Polestar/Volvo cars, you will always get a USB permission popup when starting from cold boot.

However in this log, as I would expect, the `USBDummyActivity` is trampolining the permitted USB device to the service, as designed:
```
2024-05-17 07:30:30.123 [DEBUG   ][14324-14324][AudioBrowserService     ] onStartCommand(intent=Intent { act=de.moleman1024.audiowagon.ACTION_START_SERVICE_WITH_USB_DEVICE dat= cmp=de.moleman1024.audiowagon/.AudioBrowserService (has extras) }, flags=0, startid=1)↲
2024-05-17 07:30:30.123 [DEBUG   ][14324-14324][AudioBrowserService     ] Service was started from USBDummyActivity, forwarding broadcast↲
...
2024-05-17 07:30:30.174 [DEBUG   ][14324-14397][USBIntBCRecv            ] Broadcast with action de.moleman1024.audiowagon.USB_ATTACHED received for USB device: ...
...
2024-05-17 07:30:30.189 [DEBUG   ][14324-14413][USBDevPerm              ] USB device USBMediaDevice{Kingston DT microDuo 3C(2385;5806;/dev/bus/usb/001/004;-888768790)} has permission: GRANTED↲
...
2024-05-17 07:30:31.309 [INFO    ][14324-14413][USBDevConn              ] Successfully initialized filesystem at: 2024-05-17T07:30:31.309+0200 (uptimeMillis=187078 elapsedRealtime=187078)↲
```

This should also work after unplugging and replugging the USB device and after sleep mode.
If someone has a Renault car with AAOS they could try this and show it to Volvo/Polestar users (it is the same AudioWagon app).


In Polestar and Volvo cars you will see these kind of log messages instead and USBDummyActivity will never be called:
```
Requesting permission to access device
...
Waiting for user to grant permission
```

**Comment by kingstonwa** [comment] 2024-05-18 23:38
I just submitted a support ticket to Volvo USA and here is what they said:

If there is a USB drive being utilized with the vehicle. That message will appear on the screen when the vehicle is started. This message in the vehicle cannot be removed or disabled. We understand that your experience is not to your expectation and we apologize for any inconvenience. Thank you for being part of the Volvo family.

**Comment by petard** [comment] 2024-05-28 21:06
What's confusing to me is the checkbox in the permission dialogue. It suggests the user choice is saved, which is the desired behaviour. Curious if Volvo AAOS ignores that value when launching the app or it never gets saved in the system in the first place.

**Comment by MoleMan1024** [comment] 2024-06-24 18:05
> It may be worth noting that something similar happens in the Volvo XC40. Sometimes when replugging the USB device audio will start playing without pressing the ACCEPT button.

Please provide a log file if you encounter this, I have never seen this happen.

**Comment by petard** [comment] 2024-06-25 07:31
Curious what the root cause for the issue of seeing the permission pop-up every time. I'd like to think the app asks for certain Android permissions, which are then stored by Android. Similar to the privacy permission visible under Settings for every app.

Is this supported by stock AAOS but Volvo choose to not correctly implement it in their AAOS version?

**Comment by MoleMan1024** [comment] 2024-06-25 08:09
> Is this supported by stock AAOS but Volvo choose to not correctly implement it in their AAOS version?

Indeed, in a unmodified AAOS 10 or 11 or 13 build for emulator (or when installing such a build on a mobile phone) the permission is stored persistently and it works as expected. Depending on timing this is also the behaviour you see in Renault cars. It even works fine when installing on a regular Android tablet.

Volvo/Polestar have either deliberately or by accident broken this functionality. The intended behaviour of the car-usb-handler is shortly described above [in my comment](https://github.com/MoleMan1024/audiowagon/issues/133#issuecomment-1864951717) and is also mentioned several times in the source code.

I cannot tell exactly what is broken exactly, as AAOS in Polestar/Volvo cars has not been rooted (yet?) so I have no possibility to debug this further, I can only see my own app's logging.

**Comment by MiStsGit** [comment] 2024-12-16 17:12
As an owner of an Renault R5 E-tech since two weeks, I soon installed Audio Wagon because of the stupid original USB support app.

Unfortunately this problem around the access permission disclaimer is not only present at all. Even worse, the behavior is unpredictable: 
- sometimes the car plays music without raising the disclaimer (perfect ...)
- sometimes it wants to get acknowledged the disclaimer (rather inconvenient ... but somehow acceptable)
- sometimes it denies playing files and does not show the disclaimer (inacceptable)
 
In the latter case, the only workaround I found so far is to switch to another source, then switch back to Audio Wagon ==> the disclaimer pops up and can be acknowledged.

**Comment by MoleMan1024** [comment] 2024-12-17 06:01
@MiStsGit 
>     * sometimes the car plays music without raising the disclaimer (perfect ...)

And that is exactly what does _not_ happen in Volvo/Polestar cars, that was my whole point. 

>     * sometimes it wants to get acknowledged the disclaimer (rather inconvenient ... but somehow acceptable)
>     * sometimes it denies playing files and does not show the disclaimer (inacceptable)

This might happen due to timing problems when powering on the car. Unfortunately I don't have such a car available for testing and there is no emulator image available anywhere that behaves this way. You could send some log files to me as described here that show the issue https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue then I can take a look at this.

**Comment by kingstonwa** [comment] 2024-12-17 15:41
@MiStsGit I've had the same issue for the past year on my 2023 Volvo which runs Android auto. This seems to be an issue with the manufacturer and/or Android auto and beyond the control of our developer. I'm hoping someday it will be resolved but I'm not holding my breath!

**Comment by MoleMan1024** [comment] 2024-12-17 16:00
> @MiStsGit I've had the same issue for the past year on my 2023 Volvo which runs Android auto. 

To nitpick: 
The AudioWagon app only runs on **"Android Automotive"** which is an operating system + Android framework built into a car's headunit. 
**"Android Auto"** is something completely different that runs on your mobile phone and connects to your car via cable or Bluetooth.

> This seems to be an issue with the manufacturer and/or Android auto and beyond the control of our developer. 

The issue is out of my control **for Volvo/Polestar only**, they are missing a piece of code from Google I assume (let's see what happens with the [recently announced integration of wired "Android Auto" via USB coming in the next Over-The-Air update](https://www.polestar.com/us/manual/polestar-2/2024/software-updates/) ...). 

**For Renault cars** the required piece of Google code is integrated (otherwise @MiStsGit and others would see the permission popup always, like with Volvo/Polestar). So here I can influence the behaviour of the popup to a certain extent, but I need log files from a car to understand why it behaves differently sometimes. 

Development for mobile phones is easier, I can easily buy multiple phones for testing but I can not afford multiple cars just for debugging 😉

**Comment by kingstonwa** [comment] 2024-12-17 16:18
@MoleMan1024  I just updated my Volvo to v.33.16 and the blue popup still shows :-(

**Comment by MiStsGit** [comment] 2024-12-17 16:58
First of all: I am quite sure AudioWagon App cannot solve this problem. This access control (disclaimer) is most likely intended as a security feature, originally. Let's be happy that it not yet requires a mandatory two-factor authentification ;-). A good result from my point of view would be a stable/reproducable behavior ALL the time, for all those people who are at the mercy of technical stuff simply working reliably, because it is neither their profession nor hobby ...

I just went into my R5 to obtain the stick with logfiles ... :-( ... the writing of logfiles was not yet enabled, so I enabled them for the next time(s). During this particular access, I had the scenario with the disclaimer popping up (tiresome, but in the end acceptable), playback was possible. Due to the logs not yet on, this case is lost.

Within the next days, I will try to catch each of the three sequences I had described above. As soon as I have them all, I will email them.

SW-versions involved are:
AudioWagon: 2.8.0
AAOS: 1.4.604945098-release

**Comment by Penanders** [comment] 2024-12-17 18:50
@MoleMan1024 
Hi,
something has changed with the latest update 3.3.16 on my Volvo XC40. The popup still appears, but the app works even without accepting permissions. Now it is also possible to start the app when the car is running. Maybe you can investigate further.
Thanks for everything

**Comment by MiStsGit** [comment] 2024-12-18 15:43
The car was used today for several short ways. Sometimes the disclaimer showed up, sometimes not (personally I guess this ist the case when the car did not fall asleep since the driving cycle before). Sometimes music was on, sometimes not.

Faster than expected, we again encountered the situation of 
- stick (still) present - it was present all the time today and the days before
- no replay possible due to "missing permission", but no Popup to grant permission, see picture (the car runs in Germany ...)

![no replay possible](https://github.com/user-attachments/assets/157a97bf-bde9-4ad8-9587-0455dd2946e4)

This is the case which is really kind of annoying. Luckily, I found a better way to overcome this situation than pulling the stick, because it saves the time of the content scan after re-plugging:
- enter settings of AudioWagon ==> Popup shows up ==> "ok" ticked ==> settings left
- AudioWagon continued with the last song played previously (thumbs up)

For me, this looks like the Popup being blocked/hidden somehow in this situation.

All logfiles of today will be sent soon by email.

**Comment by MoleMan1024** [comment] 2025-01-04 10:02
> @MoleMan1024 Hi, something has changed with the latest update 3.3.16 on my Volvo XC40. The popup still appears, but the app works even without accepting permissions. Now it is also possible to start the app when the car is running. 

I do not have this software yet in my own car, right now it is available in workshops only. As soon as it is available via OTA update, I will check. However it looks like Volvo/Polestar has really done something regarding persistant USB permission in most recent software update: I see some indications that support this in the Crashlytics logs I receive, this might mean the USB permission popup could be fixed "soon".

**Comment by petard** [comment] 2025-01-04 10:13
Since upgrading to 3.3.16 sometimes I do not get asked for the permission again. It is persisted across car starts. So hopefully things will get fixed for good soon by  Volvo

**Comment by kingstonwa** [comment] 2025-01-04 16:03
On my Volvo C40 when I select Audiowagon from the main menu it shows "no audio files", I have to hit the gear icon which seems to force the blue perm popup. I acknowledge then hit the back arrow to load the playlist. I have noticed that once in a while, especially after a reboot of the entertainment system, AW will start playing without the perm popup. I gues we're getting closer to complete non-obtrusive performance.

**Comment by MoleMan1024** [comment] 2025-03-19 19:16
This can be fixed after 4 long years with Polestar/Volvo car version 3.4.4 or higher and the upcoming AudioWagon release 2.8.7 or higher.

**Comment by babinecm** [comment] 2025-03-27 10:26
Unfortunately, it's not fixed. They made some changes, but the pop-up still appears sometimes. It's random, sometimes it shows up once after starting the car, other times every time the car starts.
I have Volvo S60, system version 3.3.16, AudioWagon version 2.8.7.

**Comment by petard** [comment] 2025-03-27 10:33
It’s not fixed with 3.3.16 but requires 3.4.4 Android in your car. This update can only be installed at the dealer. OTA was pulled by Volvo.On 27. Mar 2025, at 11:26, Milan Babinec ***@***.***> wrote:﻿
  Unfortunately, it's not fixed. They made some changes, but the pop-up still appears sometimes. It's random, sometimes it shows up once after starting the car, other times every time the car starts.
I have Volvo S60, system version 3.3.16, AudioWagon version 2.8.7.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



babinecm left a comment (MoleMan1024/audiowagon#133)
Unfortunately, it's not fixed. They made some changes, but the pop-up still appears sometimes. It's random, sometimes it shows up once after starting the car, other times every time the car starts.
I have Volvo S60, system version 3.3.16, AudioWagon version 2.8.7.

**Comment by MoleMan1024** [comment] 2025-03-27 10:45
> Unfortunately, it's not fixed. They made some changes, but the pop-up still appears sometimes. It's random, sometimes it shows up once after starting the car, other times every time the car starts. I have Volvo S60, system version 3.3.16, AudioWagon version 2.8.7.

I don't see the popup at all anymore in my car.

Please create a new bug ticket with exact description as explained [here](https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue)

**Comment by iuddite** [comment] 2025-04-06 12:14
Polestar 2 owner with v3.4.4 installed and the USB permissions popup still remains.

I disable it every time but it keeps returning.

**Comment by MoleMan1024** [comment] 2025-04-06 13:46
> Polestar 2 owner with v3.4.4 installed and the USB permissions popup still remains.
> 
> I disable it every time but it keeps returning.

Please create a new bug ticket with exact description as explained [here](https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue). I suspect the timing of how long you leave the car could be important.

**Comment by ersmiller** [comment] 2025-06-04 20:09
Just thought I'd mention that this also happens in the 2025 Chevy Equinox EV That I got a couple weeks ago.
  Here's the actual error screen on that car:

![Image](https://github.com/user-attachments/assets/5b9513fe-f421-4d88-bec3-540d452d5531)
  Hope this helps.

**Comment by wimjanse** [comment] 2025-06-05 05:40
Same with my Volvo XC60-T6-hybrid, setting the tick-box does not help.

**Comment by MoleMan1024** [comment] 2025-06-05 06:22
@ersmiller , @wimjanse : The current ticket is closed, nothing else will be done here, this should be working most of the time if you have Volvo car software version 3.4.4 or higher. Personally I have only seen the popup appear once in the last 2 months or so.

If you want me to look into the problem seen in your cars, please provide a log file and detailed description as explained [in the documentation](https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue) and send to me or create a new issue here.

**Comment by ersmiller** [comment] 2025-06-08 05:23
> [@ersmiller](https://github.com/ersmiller) , [@wimjanse](https://github.com/wimjanse) : The current ticket is closed, nothing else will be done here, this should be working most of the time if you have Volvo car software version 3.4.4 or higher. Personally I have only seen the popup appear once in the last 2 months or so.
> 
> If you want me to look into the problem seen in your cars, please provide a log file and detailed description as explained [in the documentation](https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue) and send to me or create a new issue here. For non-Polestar/Volvo cars I have no way to reproduce this, a bug report with a log file is a must here, otherwise nothing will happen.


1)	Got in car and pressed the brake pedal (that turns it on).  A few seconds later, AudioWagon asked for permission to access the USB thumb drive my music is stored on.

2)	I’ve already given AudioWagon permission, so I expected it to just start playing music without the popup happening first.

3)	This happens every time I start the car.
	Useful timestamp: 2025-06-06 17:23:04.788

4)	AudioWagon version: 2.9.1
	
5)	Chevy Equinox EV 2025
	Android:	12
	Android Security patch level: April 5, 2024
	Kernel:	5.4.254-qgki-ga9e7a955a2b6-dirty
			      #.1Wed Jun 19 00:37:52 EDT 2024
	Build number:	burmese_orange-user 12 W52E-176.1.2-M170-SQBR5-250.2 239 release-keys

6)	Log files attached.

[audiowagon_2025-06-06_17-23-14.log](https://github.com/user-attachments/files/20642952/audiowagon_2025-06-06_17-23-14.log)
[audiowagon_2025-06-05_17-21-56.log](https://github.com/user-attachments/files/20642950/audiowagon_2025-06-05_17-21-56.log)
[audiowagon_2025-06-06_06-58-30.log](https://github.com/user-attachments/files/20642951/audiowagon_2025-06-06_06-58-30.log)

**Comment by MoleMan1024** [comment] 2025-06-08 06:28
@ersmiller : Thank you for the log files. Based on those you seem to have the same problem as originally in the Volvo/Polestar where a piece of code from Google is likely missing or disabled by General Motors (see [above](https://github.com/MoleMan1024/audiowagon/issues/133#issuecomment-2117657712) ). There should be a `USBDummyActivity` started in the log files at some point, but I never see it. That means the permission popup will always come and there is nothing I can do about it. You need to complain to General Motors so they change their software.

**Comment by MoleMan1024** [comment] 2025-08-17 05:45
See also #182 where the permission popup is still shown sometimes for another Volvo driver
